#!/bin/bash

cd ~

echo "===> [1/4] Thiết lập quyền truy cập bộ nhớ..."
if [ -e "/data/data/com.termux/files/home/storage" ]; then
    rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
sleep 2
mkdir -p /sdcard/Download

echo "===> [2/4] Cập nhật Packages Termux..."
yes | pkg update
. <(curl -s https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/termux-change-repo.sh)
yes | pkg upgrade -y

echo "===> [3/4] Cài đặt Python & Thư viện phụ thuộc..."
yes | pkg i python -y

export CFLAGS="-Wno-error=implicit-function-declaration"

pip install requests tqdm packaging --break-system-packages

echo "===> [4/4] Đang tải các file Tool..."
curl -Ls "https://autoinstallpremium.zam2109shop.vn/autoinstall.py" -o /sdcard/Download/autoinstall.py
curl -Ls "https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/zamtoolrejoinver10.py" -o /sdcard/Download/zamtoolrejoinver10.py
curl -Ls "https://zam2109shop.vn/obfzmcaitien" -o /sdcard/Download/zamtoolrejoinver10.py 

echo "===> [✓] Đã hoàn tất tải và thiết lập môi trường!"
